### ISSUE TITLE
Add Required and Title AttributeBindings

### ISSUE THREAD

**Issue by srsgores** [johnotander/ember-mailcheck#9]
For HTML5 inputs which are to have the `required` attribute, this component should be configurable.

Given the current approach, I suggest adding `required: false` to the component.  Then, [in the template](https://github.com/johnotander/ember-mailcheck/blob/master/app/templates/components/mail-check.hbs#L1):

```
{{input type=type name=name value=value placeholder=placeholder class=inputClass focus-out="mailcheck" disabled=disabled required=required title=title}}
```

Note, as well, the addition of `title`, such that the browser can display any custom messages when validation fails.

**Comment by johno** [comment]
Agreed, will publish this shortly. Thanks!

**Comment by johno** [comment]
Published to npm as `ember-mailcheck@1.2.0`.

**Comment by srsgores** [comment]
Possibly merit for another issue, but the `span` element should be replaced with a `label` element; the current configuration is inaccessible to screen readers, as there is no label associated with the `input`.

**Comment by johno** [comment]
I've been pondering this as well. I've been considering adding a `label` option for the component so one can pass `{{mail-check value=email label='email'}}` with a template like:

``` hbs
{{#if label}}
  <label>{{label}}</label>
{{/if}}

{{input}}
```

This would ensure that the label is associated with the input. Thoughts?

**Comment by srsgores** [comment]
@johnotander, no, that would not associate with the input.  You would need a `for` attribute, which is missing in your example.  There should always be a label, regardless of whether the user specified one.  I think that the label should get the `visuallyhidden` treatment if the user does not specify one.
